### PR TITLE
Automatically maintain release notes using GitHub Actions

### PR DESCRIPTION
**Pull request by mattbrictson**
This commit sets up a GitHub Actions workflow that uses Release Drafter to automatically maintain release notes on every push.

In practice this means that contributors no longer have to manually update the CHANGELOG, which is something that is easy to forget and often introduces tedious merge conflicts.

Instead, Release Drafter automatically adds the title of the PR to the GitHub release notes in a draft release, crediting the author of the PR, and linking to the PR number. Release Drafter furthermore organizes the release notes into sections according to the labels assigned to the PRs:

- Breaking
- Bug Fix
- Docs
- Feature
- Housekeeping

This also simplifies the release process for maintainers: instead of manually updating the CHANGELOG, all you have to do is press "publish" on the release draft on GitHub.

Here is an example from another project:

https://github.com/mattbrictson/airbrussh/releases/tag/v1.3.3

### CODE REVIEW

**Comment by leehambley** [comment]
I'm not thrilled about all the other emojis in the changelog, I think this is a bit unnecessary and kitschy but the rest of it looks great.

Let's give it a try?

We also need a corresponding PR in the `capistrano/danger` repo to stop the danger automates code review complaining, right?

**Comment by mattbrictson** [comment]
> I'm not thrilled about all the other emojis in the changelog

No problem, I've updated the Release Drafter config to remove the emoji.

Note that maintainers will have to remember to add the appropriate label to a PR before merging it, if they want it to be automatically categorized in the release notes. I've named all the labels starting with a **PR:** prefix: 

- PR: Breaking
- PR: Feature
- PR: Bug Fix
- PR: Docs
- PR: Housekeeping

(However if you don't use one of these labels, the PR will still automatically be added to the release notes, just in a catch-all section. So it's not a big deal if you forget.)

Should this be documented somewhere for current and future maintainers? E.g. `MAINTENANCE.md` or `CONTRIBUTING.md` (I'm not sure if there is a convention)?

> We also need a corresponding PR in the capistrano/danger repo to stop the danger automates code review complaining, right?

I [created a branch](https://github.com/capistrano/danger/tree/no-changelog) for now. I didn't want to merge it into capistrano/danger master yet because that is being used by other capistrano projects that still have CHANGELOGs.

**Comment by leehambley** [comment]
Good point, this all looks good to me, and honestly the emojis in the change-log for `airbrussh` look nice. I had assumed it would be one emoji per line and not one for each heading, with them being grouped.

Nice stuff mate, LGTM.

**Comment by mattbrictson** [comment]
Thanks! I'll add the emoji back in and get this merged. 👍

**Comment by leehambley** [comment]
Thank you for for your patience dude :pray:

**Comment by leehambley** [comment]
so pretty!

**Pull request merged**
