### PR TITLE
Cache known hosts lookup by default

### PR DESCRIPTION
**Pull request by byroot**
Followup to https://github.com/capistrano/sshkit/pull/330

To be merged at some point.

cc @mattbrictson

### CODE REVIEW

**Comment by leehambley** [comment]
TIL about http://ruby-doc.org/stdlib-2.3.0/libdoc/mutex_m/rdoc/Mutex_m.html :) thanks :+1:

**Comment by mattbrictson** [comment]
@byroot No hurry, but this will also need to be rebased at some point so we can merge it for a future release.

**Comment by byroot** [comment]
Done!

**Comment by mattbrictson** [comment]
Thanks. Could you add a brief CHANGELOG entry?

**Comment by byroot** [comment]
Done as well!

**Pull request merged**
