### PR TITLE
Quote environment variable values

### PR DESCRIPTION
**Pull request by Sinjo**
Ran into an issue this week with an environment variable which contained special shell characters, and broke deploys.

I was going to solve this with `Shellwords.escape`, but found that also escapes '$'.

I ended up taking the approach from #156 and bringing it up to date with master.

@leehambley You okay with this approach?

### CODE REVIEW

**Comment by leehambley** [comment]
Yeah, please add an entry to the changelog.

**Comment by robd** [comment]
@Sinjo I had a couple of thoughts about this.

Would it be possible to add a test for the new escaping functionality when double quotes are passed as part of the value?

This is purely a style thing, but I was also wondering if it would be clearer using a `%{}` string literal rather than escaping the double quotes, both in the tests and in `Command`. Maybe this:

```ruby
key_string = key.is_a? Symbol ? key.to_s.upcase : key.to_s
substituted_value = value.to_s.gsub(/"/, '\"')
%{#{key_string}="#{substituted_value}"}
```

**Comment by Sinjo** [comment]
@robd Keen on all those suggestions. I've modified my original commit, and added a couple more to refactor the code/tests.

Look good?

**Comment by leehambley** [comment]
Yep, looks good, particularly fond of the `%{}` for making the tests easier to read.

**Comment by robd** [comment]
@Sinjo That looks great - nice one. @leehambley could probably close #156 too I think?

**Pull request merged**
