### PR TITLE
New API for setting+configuring formatter: use_format

### PR DESCRIPTION
**Pull request by mattbrictson**
Redo of #294 to include README and CHANGELOG updates.

### CODE REVIEW

**Comment by mattbrictson** [comment]
@leehambley I've rebased the branch so that you merge this into master and replay the commits that were reverted.

Should be good to merge :+1:

**Comment by robd** [comment]
@mattbrictson I thought I had reinstated support for any output which implemented `<<`. Are you sure  this isn't implemented any more?

**Comment by leehambley** [comment]
Thanks @mattbrictson :) release due Nov 02 :)

**Comment by mattbrictson** [comment]
@robd You're right. I was skimming the README and thought it was referring to `SSHKit.config.output = $stdout`, when in fact it was referring to passing `$stdout` to the formatter. I'll fix it.

**Comment by robd** [comment]
@mattbrictson There is an argument to say perhaps we could get rid of the output config option and just allow the use_format option to take an instantiated `Formatter`:

```ruby
output = String.new		
SSHKit.config.use_format(SSHKit::Formatter::Pretty.new(output))
```

Not sure if this is better?

Also, in the docs, should it be this:

```ruby
SSHKit.config.use_format :foobar
...
SSHKit.config.use_format :foobar, :my_option => "value"
``` 
instead of 

```ruby
SSHKit.config.use_format = :foobar
...
SSHKit.config.use_format = :foobar, :my_option => "value"
```

**Comment by mattbrictson** [comment]
> Also, in the docs, should it be this

Yes I noticed that too. Fixed in #297. (My commits have been pretty sloppy today, sorry!)

**Comment by robd** [comment]
No problem - I saw you'd spotted too after I commented - thanks for sorting these.

**Pull request merged**
