### PR TITLE
Clarify output configuration option

### PR DESCRIPTION
**Pull request by robd**
Currently the docs say we support assigning an io to the `SSHKit.config.output` configuration option:

```ruby
SSHKit.config.output = $some_io
```

Unfortunately this doesn't work at all well as discussed in #243. Therefore, this PR updates the docs to remove that as a supported option. 

It also simplifies some tests which were using the `SSHKit.capture_output` method. This assigned a `String` to `SSHKit.config.output` and then dynamically extended it with a custom write method from `CaptureOutputMethods`, which also added in newlines in some cases. These tests now use the `output` option in the way suggested in the docs, ie:

```ruby
SSHKit.config.output = SSHKit::Formatter::SimpleText.new(@out)
```

This PR also re-enables and fixes the  `simple_netssh` test on the `TestNetssh` functional test, which was being ignored.

Finally, it cleans up some `setup` methods on unit tests which were duplicating the method on `UnitTest` and adds some missing calls to `super`.

### CODE REVIEW

**Comment by robd** [comment]
Hey @mattbrictson I don't think this should have any affect on Airbrussh, but I wanted to give you a heads up in case I've missed something.

**Comment by leehambley** [comment]
@mattbrictson I'll wait for an OK from you before merging this, if you'd be kind enough to test before hand!

**Comment by mattbrictson** [comment]
I'll try to review later today (PDT).

**Comment by mattbrictson** [comment]
Looks good to me! I tested this branch and it works fine. :+1:

**Comment by leehambley** [comment]
:busts_in_silhouette: teamwork!

**Pull request merged**
