### PR TITLE
Fix uninitialized instance variable / overridden function warnings.

### PR DESCRIPTION
**Pull request by xavierholt**
Found myself cleaning up some Ruby warnings while testing a branch earlier today, so I thought I'd finish the job and help out with https://github.com/capistrano/sshkit/issues/344

Couple notes:
 - Most changes are simply setting things to `nil` in `initialize` methods.
 - Identical `unindent` functionality is provided by the unindent gem, so the monkeypatch version isn't needed any more.
 - Part of my fix makes `group_size` and `wait_interval` publicly readable on the runners.  It seemed odd to have them writeable but not readable, so I felt okay making the visibility change.  If that's not okay, let me know and I'll revert that part.

### CODE REVIEW

**Comment by leehambley** [comment]
LGTM :) thanks for the contribution - Should I merge right now, or would you like to credit yourself in the changelog ?

**Comment by robd** [comment]
Hey - apologies for chiming in out of nowhere! 

One thing I noticed here (unless I missed something) is that the `unindent` method is only called in one place (`test/functional/backends/test_netssh.rb`). I wondered if it would be better to remove the SSHKit dependency on the `unindent` Gem, and move the unindent method from `test/unit/core_ext/test_string.rb` to `test_netssh.rb`.

I guess the only other thing to check is whether the build is passing - see discussion here: https://github.com/capistrano/sshkit/issues/351

**Comment by xavierholt** [comment]
@robd:  Updated with an even further simplification - scrap the unindent method entirely!

@leehambley:  No need - I got credit for my actual bugfix, and this is just trivial cleanup.  I'm okay to merge whenever.  Not sure if https://github.com/capistrano/sshkit/issues/351 is relevant.  It'll pass CI; the issue only shows up when running on a host with a non-empty known_hosts file...  Just let me know if you'd like me to rebase after the fix is in.

**Comment by robd** [comment]
> scrap the unindent method entirely!

👍 Even better!

**Comment by mattbrictson** [comment]
#351 is now fixed in master. Can you rebase, please?

**Comment by xavierholt** [comment]
@mattbrictson:  Rebased.  Cheers!

**Comment by mattbrictson** [comment]
Acceptance tests pass. ✅ 

@leehambley I'll leave the merge to you.

**Comment by leehambley** [comment]
Thanks @xavierholt and for the sanity checking @mattbrictson

**Pull request merged**
