### PR TITLE
call #to_s on remote so Pathnames don't go :boom:

### LINKED ISSUE #409: "Embrace String#start_with?" fails when called via Cap
Commit https://github.com/capistrano/sshkit/commit/e715e05d491bbd5c795e380d1d15019727cbc4a3

When calling `upload!` via Cap, this call fails due to `remote` being a Pathname instead of a string.

    SSHKit::Runner::ExecuteError: Exception while executing as deploy@example.com: undefined method `start_with?' for #<Pathname:/ebs/webapps/xxx/staging/releases/20171109202937>
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

    Caused by:
    NoMethodError: undefined method `start_with?' for #<Pathname:/ebs/xxx/staging/releases/20171109202937>
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/netssh.rb:66:in `upload!'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sekrets-1.10.0/lib/sekrets/tasks/sekrets.rake:8:in `block (4 levels) in <top (required)>'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `run'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'

[Here is the task that's calling upload!](https://github.com/ahoward/sekrets/blob/18828c9cdd9a0e9af7f89c55053a53f9383aa55e/lib/sekrets/tasks/sekrets.rake#L8)

### PR DESCRIPTION
**Pull request by UnderpantsGnome**
This fixes #409

### CODE REVIEW

**Comment by sj26** [comment]
Sorry, I didn't realise those methods accepted Pathname :-(

Perhaps we should also add a test to make sure this doesn't break again?

**Comment by UnderpantsGnome** [comment]
I can put together a test for this, but I don't have Vagrant installed and I don't really want to install it :pensive:

**Comment by UnderpantsGnome** [comment]
I added tests, the local one passes, I can't run the netssh one without vagrant. Let me know if this is good and if you want me to squash and update then CHANGELOG

**Comment by sj26** [comment]
I've got it all set up, let me give it a quick go.

**Comment by sj26** [comment]
```
SSHKit::Backend::TestNetssh
  test_upload_string_io                                           PASS (1.05s)
  test_interaction_handler                                        PASS (0.01s)
  test_execute_raises_on_non_zero_exit_status_and_captures_stdout_and_stderr PASS (0.01s)
  test_test_does_not_raise_on_non_zero_exit_status                PASS (0.01s)
  test_capture                                                    PASS (0.01s)
  test_upload_and_then_capture_file_contents                      PASS (0.01s)
  test_upload_via_pathname                                        PASS (0.01s)
  test_simple_netssh                                              PASS (0.03s)
  test_env_vars_substituion_in_subshell                           PASS (0.01s)
  test_upload_within                                              PASS (0.02s)
  test_upload_large_file                                          PASS (9.27s)
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
  test_ssh_option_merge                                           PASS (1.06s)
```

:+1:

**Comment by sj26** [comment]
(I just realised Travis also runs these and they all passed anyway.)

**Comment by mattbrictson** [comment]
Thanks for the quick turnaround on this! Could add a CHANGELOG entry?

**Comment by UnderpantsGnome** [comment]
Updated the changelog and squashed commits. Not sure why Danger is blowing up.

**Comment by mattbrictson** [comment]
Danger is blowing up because:

> Please put the * Your contribution here! line back into CHANGELOG.md.

Could you take care of that? Thanks!

**Comment by UnderpantsGnome** [comment]
Ah Mondays... Danger is happy again.

**Comment by mattbrictson** [comment]
Thanks for your help!

**Pull request merged**
