### PR TITLE
Ability to specify custom runner

### PR DESCRIPTION
**Pull request by kirs**
This patch enables ability to specify my own runner class.

```ruby
module SSHKit
  module Runner
    class MyParallel < Abstract
    # ...
    end
  end
end

on roles(:web), in: :my_parallel do
  # …
end
```

### CODE REVIEW

**Comment by mattbrictson** [comment]
I have no strong feelings on this one either way. @leehambley Any objections?

Before a merge we would also need:

* CHANGELOG entry
* Unit test
* Rebase against current `master` so that Travis checks pass

**Comment by leehambley** [comment]
I'd rather it took a class name honestly.

**Comment by kirs** [comment]
The idea about class name sounds good. I'll change it. Basically, using custom runner is a use-case from our setup at @Shopify.

**Comment by leehambley** [comment]
I thought you were working at Giant Martians ?

**Comment by kirs** [comment]
I've reworked it a bit:
- `in:` accepts a class name
- you can globally set the default runner with `SSHKit.config.default_runner` (which is still `parallel` by default)

WDYT? I'll add the changelog and tests if we're good with implementation.
@leehambley it's Shopify since 2016 :boom:

**Comment by leehambley** [comment]
Go ahead :)

**Comment by kirs** [comment]
Done. Please have a look on tests :)

**Comment by leehambley** [comment]
@kirs Travis blew up mate, could you take a look?

**Comment by kirs** [comment]
@leehambley fixed.

**Pull request merged**
